server:
  port: 80
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
    context-path: /chapter02
  tomcat:
    uri-encoding: utf-8
    max-threads: 500
  ssl:
    key-store: sang.p12
    key-alias: tomcathttps
    key-store-password: 123456

book:
  name: 三国演义
  author: 罗贯中
  price: 30

#my:
#  name: 江南一点雨
#  address: China
#  favorites:
#    - 足球
#    - 徒步
#    - Coding

my:
  users:
    - name: 江南一点雨
      address: China
      favorites:
        - 足球
        - 徒步
        - Coding
    - name: sang
      address: GZ
      favorites:
        - 阅读
        - 吉他